require("sets")
require("keymaps")

require("packer-setup")
require("after.fugitive")
require("after.gitsigns")
require("after.telescope")
require("after.treesitter")
require("after.lsp")
require("after.lualine")
require("after.nvim-tree")
require("after.undotree")
require("after.ufo")
require("after.vim-maximizer")
